### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#14]
@redchillipadi Adrian,

There's no real way to message people on Github. Ah well.

I had a talk with Amy (Amynka), and she said that if you want to help with OpenCV you can. I showed her the issue report on CUDA to show how you know a lot of technical details and can research them. As you know, CUDA is not an easy thing to do in ebuilds. That's an understatement. OpenCV is not an easy thing as well, which required some fun hacks to make work. If you breath on OpenCV the wrong way, it will break. haha. Well, that's almost true. 

As an added bonus, she has built several robots and has lots of OpenCV experience. I joked with her that you two are a match made in heaven. I like jokes and funny things.

You should be able to reach her on IRC on #gentoo-proxy-maint. The devs there know a lot! They will also be the ones to review the ebuilds before they are committed to the portage tree.

Hmm. I wonder if this will work...
tagging @Amynka

Cheers.

**Comment by redchillipadi** [comment]
Thanks for the introduction, Jon,  I will head over to IRC tonight to see if 
she is there.

Cheers,
Adrian

**Comment by dracwyrm** [comment]
No problem. You know your stuff, so the more people that are skill working on it the better. :)
