### ISSUE TITLE
media-libs/Ptex: Considered Ready?

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#15]
To track a milestone.

**Comment by dracwyrm** [comment]
I'm thinking Ptex is ready for inspection. It's the smallest ebuild, but it compiles in multiple different situations, which can break even the simple-ist of ebuilds. It also seems to work.

**Comment by redchillipadi** [comment]
I also feel that it is ready. Lets start with ptex

**Comment by dracwyrm** [comment]
Sweet. If milestones work right, then there should be a progress bar, which is why I wanted a milestone in the first place. :P

**Comment by dracwyrm** [comment]
Whoo. There is a progress bar. :D Now it feels like we are progressing.
