### ISSUE TITLE
media-libs/osl: Considered Ready?

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#16]
To track a milestone.

**Comment by dracwyrm** [comment]
Cg overlay has osl in media-gfx. Is this a lib or a gfx? It's hard to choose a category. :P Also, should it be osl or OpenShadingLanguage, or openshadinglanguage? There are capital named ebuilds. I like osl since it's short, but is it right?

**Comment by redchillipadi** [comment]
We are using it for libOSL.. which I felt makes it a library. However it also contains a compiler for the shading language so you could argue either way. Although it is not a full blown graphics application in itself and I think most people would use it a a library accessed from another application such as blender.

A lot of the blender pages refer to it as osl, which I also prefer beause it is short, but it is referred to as openshadinglanguage in archlinux. I think it gets too confusing mixing upper and lower case in a case sensitive file system, so prefer to stick to lower case.

**Comment by dracwyrm** [comment]
Fair enough. That's why I ask questions. :) I'm a prolific question asker, in case you didn't notice.

**Comment by dracwyrm** [comment]
Is this ready then? I can't think of anything else to do with it for now.

**Comment by redchillipadi** [comment]
I think its ready. 

It requires openexr, which needs the -abi_x86_32 or my fix from Bug 585846, but people using blender will unlikely really want it to run in 32 bit mode anyway.

I am currently looking at enhancing it to support boost 1.61 and llvm 3.6+, but we decided these should not be show stoppers.

**Comment by dracwyrm** [comment]
I think converting it to 1.61 and 3.6+ will take a long time. :( The good news, is that llvm 3.6+ code is somewhat in master trunk of git.

I think Blender will be run in 64 bit as well because of the memory address space. Rendering takes a crap ton of memory sometimes.

hmm. I need to look up the abi thing.

**Comment by redchillipadi** [comment]
If necessary we can just depend on bug 585846, this may push for it to be patched sooner. Making it more flexible for later versions will take some time and is a future enhancement only.

**Comment by dracwyrm** [comment]
I made blender depend on that bug on b.g.o. :)
