### ISSUE TITLE
media-gfx/openvdb: Considered Ready?

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#18]
To track a milestone.

**Comment by redchillipadi** [comment]
This one still tries to install the python documentation into /usr/lib/include so it needs this fixed before we can call it ready.

**Comment by dracwyrm** [comment]
Damn. Thought I got that fixed. Unless I forgot to push it a while back and then overwrote it.

**Comment by dracwyrm** [comment]
python module is now installed to here:
/var/tmp/portage/media-gfx/openvdb-3.1.0/work/install/usr/share/doc/openvdb/html/python/

**Comment by redchillipadi** [comment]
Just checked it and it worked for me this time. I didn't have any other issues left so do you think we can submit this too?

**Comment by dracwyrm** [comment]
Sorted and closing to update progress bar. :)
