### ISSUE TITLE
media-gfx/blender: Considered Ready?

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#19]
To track a milestone.

**Comment by redchillipadi** [comment]
I've got nothing left to do on this, other than our enhancement for selecting and compiling the cuda binaries during the ebuild. I think we should as for a review here as well, as we have spent over a week on polishing this and can only test so much between our two systems.

**Comment by dracwyrm** [comment]
All I can say is that thank {your deity of choice} that we have different GPUs. Some of things we done would not be possible otherwise.

Also, I have been debating this in my head for days:
To remove 32 bit support (remove x86 keyword)
or
To keep 32 bit support
That is the question here. (Hamlet in the modern world).

**Comment by redchillipadi** [comment]
I feel we should try to keep 32 bit support in, because providing blender is capable of doing it, we should not limit the user the option to run blender on minimal hardware if they so choose. Not that I can think of a platform with a CUDA 2.1 card which only supports 32 bit offhand

**Comment by redchillipadi** [comment]
I also thank the deity that we have different gpus but also that mine is the better one :P

**Comment by dracwyrm** [comment]
Amd will catch up to the current line of nVidia cards in 5 years time. :D
