### ISSUE TITLE
Adrian to file maintainer requests on b.g.o.

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#20]
You need to file a request for maintainership of the five programs.
[Example](https://bugs.gentoo.org/show_bug.cgi?id=586160)
Your one would be the opposite of the text there: your name co-maintain with me. :) I still need to do two of them. You should have emails from the ones I did already.

Then I can add you to the assignee of Blender and co.

**Comment by redchillipadi** [comment]
I have submitted the bug requests. There are two left for you to submit, the reciprocal of Bug 586374 and Bug 586376

**Comment by dracwyrm** [comment]
I just added those two now. That's all sorted then. :)

**Comment by dracwyrm** [comment]
Oh. Forgot, you need to do one like this:
https://bugs.gentoo.org/show_bug.cgi?id=585734
Then your maintainership requests block that one. Like the ones I have do. You can use all those as an example. :)

**Comment by redchillipadi** [comment]
Done, see bug 586392

**Comment by dracwyrm** [comment]
Cool. The way it's done is very confusing, so sorry I forgot that one. XD
