### ISSUE TITLE
media-gfx/openvdb: Make a new use flag for pdfdoc

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#3]
There are two types of documentation that can be produced. The regular html pages and then the PDF version. The PDF version requires the whole latex library, so it should be optional for users who really want the pdf, though I suspect it's online somewhere.

**Comment by dracwyrm** [comment]
I may have it done. Will do testing later. Exhausted.

**Comment by redchillipadi** [comment]
I can't find the pdf file when I compile with pdfdoc. I have the /usr/share/doc/openvdb/html documentation, but it doesn't appear to be creating the pdf.

**Comment by redchillipadi** [comment]
The pdf can be created when I pass emake pdfdoc EPYDOC=pdoc but the Makefile has no code to install it.

There is a lot of unneeded creation of documentation. All the html docs are created for each python implementation only to be removed after each emake clean including just before calling emake install

I am working on a patch to explicitly create the documentation once and install it from the ebuild

**Comment by dracwyrm** [comment]
@redchillipadi: Should the documentation go into each python version modules folder? Isn't specific to a version, or universal? Why the heck does it make a PDF and not install it.

**Comment by redchillipadi** [comment]
Commit https://github.com/dracwyrm/gentoo-ebuilds/commit/51fec031adebae6ec36886b434452668a5553e38 fixes the pdfdoc issue on my system. The PDF is created and installed only when pdfdoc is specified.

**Comment by dracwyrm** [comment]
That's good work there. How many times do we need to patch the installer to make it work? I submitted a patch upstream with some simple fixes, might need to submit another. -_-

**Comment by redchillipadi** [comment]
We are fighting the build system to make it accept multiple python targets when it was designed for a single python target. Using PYTHON_SINGLE_TARGET would make for less maintenance. But multiple versions will be useful if we ever need to support coinstallation of multiple versions of blender (eg if users want to use add ons for legacy projects which are not supported by the new python/blender version, but also use newer blender features for other projects)

**Comment by dracwyrm** [comment]
Also, a person could use OpenVDB by itself. The plugins will allow someone with legacy python 2.7 code to be able to use OpenVDB, and Blender can make use of the 3.5 plugins. Since it is a stand alone program, we need to consider more use cases rather than just Blender. Though, it's more work on us, but more compatible to all users. :) OpenVDB actually supports multiple pythons, but only one compile at a time, so in theory, you could manually install this three times with three different python locations, we are just forcing it into one install. Not easy.
