### ISSUE TITLE
media-gfx/openvdb: Add python use flag to make python optional

### ISSUE THREAD

**Issue by dracwyrm** [dracwyrm/gentoo-ebuilds#4]
Python is only used to compile a module for python, but if you don't want that module, then there's no need for all the dependencies, mainly NumPy. This will completely bypass module compilation, which takes longer than the regular module.

**Comment by dracwyrm** [comment]
This needs to be double checked to make sure everything is alright.

**Comment by redchillipadi** [comment]
The python flag appears to work as expected.

Building openvdb with only X and openvdb-compression compiles successfully without building any of the python modules.

When specifying python but no docs or pdf it adds the numpy dependency and builds the python modules as it should to create pyopenvdb.so.

I am currently attempting to sort out the blocker which prevents me from adding the documentation use flags.

**Comment by redchillipadi** [comment]
I thought I already added this comment but it appears to have disappeared. I have been able to add the documentation use flags by updating dev-python/pdoc to add python3_5 to PYTHON_COMPAT and mark most of texlive as ~amd64. This creates the html documentation successfully, but the pdfdoc doesn't appear. I will look into it tomorrow.

**Comment by dracwyrm** [comment]
@redchillipadi: Thanks for the info. The Makefile says that's it's supposed to produce a PDF with latex installed. Do I need to patch that file yet again?

**Comment by redchillipadi** [comment]
This as well as #3 are fixed by commit 51fec031adebae6ec36886b434452668a5553e38
