### ISSUE TITLE
media-gfx/openvdb compiles but I don't see it

### ISSUE THREAD

**Issue by redchillipadi** [dracwyrm/gentoo-ebuilds#9]
I have compiled blender with openvdb support, but can't find any tutorials on what it does or how to use it. Am I meant to be able to add a particle mesher modifier or a new shader node?

**Comment by dracwyrm** [comment]
I wonder if you are supposed to script to it in Blender, hence the python modules, maybe? It might say in the Makefile what to do, as some things are in there with explanations.

**Comment by dracwyrm** [comment]
There's a sample project here:
https://wiki.blender.org/index.php/User:Kevindietrich/OpenVDBRendering
There's a download on that page, it might have OpenVDB enabled, but on that page, it says that it integrates into cycles itself.

And
http://blenderartists.org/forum/showthread.php?393677-OpenVDB-Test&p=3020959

**Comment by dracwyrm** [comment]
Ah. I think we need this set of patches:
https://developer.blender.org/D1008

**Comment by redchillipadi** [comment]
I have read both of those pages. The blend file displays a cube completely filled by orange particles, I think it must need to be told to use the fire.vdb data to get it to work, but couldn't see any option.

I will also look into whether our version includes the openvdb patches, but as you say I thought it was already integrated into cycles.

**Comment by dracwyrm** [comment]
Yeah. It's supposed to be integrated into 2.77. Unless they forgot something that is in that patch?

**Comment by redchillipadi** [comment]
Just had a thought, openvdb-compression is an ungainly name for a USE flag. Should we rename it to blosc?

**Comment by dracwyrm** [comment]
It is a pretty long name. I think in the original ebuild, it was descriptive for what it does. No body would know what blosc would do and may be too lazy to look that up. But with a name like compression tells people what it does. Also, in blender, it tells people it's part of the openvdb package.

This is a tricky one. There's points for both ways.

**Comment by redchillipadi** [comment]
I am in two minds about openvdb-compression vs blosc also. It was painful having to type it in the documentation repeatedly. But for a user they only need to set it once in their package.use and its done. So lets leave it as it is so that people know what it does..

**Comment by dracwyrm** [comment]
That makes sense. It's one of those things that makes a dev's life hell, but a user's life easier. Unfortunately (or rather fortunately), this is about the users.

**Comment by redchillipadi** [comment]
I have found the trick to openvdb. My picture of how to find the panel is in another post. To make it so that you can edit the smoke cache, you just need to save the file. Thanks to http://community.cgcookie.com/t/i-cant-change-anything-in-the-smoke-cache/2177 for the answer!

Instructions for testing are:

In blender, set the renderer to Cycles Renderer. Go to the physics panel and enable physics for Smoke. In the smoke section select Domain. Save the file to enable editing of the smoke cache. Change File Format to Openvdb and select Blosc compression if desired.

If this works for you then I think we can close this issue. I will update the wiki page

**Comment by dracwyrm** [comment]
I think we can close this and fix the wiki. :) Very good hunting on that one.
